[symlinks]
".Xmodmap" = "/home/anna/.Xmodmap"
".emacs.d/anna-conf.org" = "/home/anna/.emacs.d/anna-conf.org"
".emacs.d/init.el" = "/home/anna/.emacs.d/init.el"
"fish/config.fish" = "/home/anna/.config/fish/config.fish"
"fish/fish_variables" = "/home/anna/.config/fish/fish_variables"
"fish/functions/cr.fish" = "/home/anna/.config/fish/functions/cr.fish"
"fish/functions/fish_greeting.fish" = "/home/anna/.config/fish/functions/fish_greeting.fish"
"fish/functions/fish_prompt.fish" = "/home/anna/.config/fish/functions/fish_prompt.fish"
"nvim/init.vim" = "/home/anna/.config/nvim/init.vim"
"polybar/custom/polybar-now-playing-script" = "/home/anna/.config/polybar/custom/polybar-now-playing-script"
"polybar/launch.sh" = "/home/anna/.config/polybar/launch.sh"
"rofi/config.rasi" = "/home/anna/.config/rofi/config.rasi"
"rofi/dmenu-custom.rasi" = "/home/anna/.config/rofi/dmenu-custom.rasi"

[templates]
"i3/config" = "/home/anna/.config/i3/config"
"kitty/kitty.conf" = "/home/anna/.config/kitty/kitty.conf"
"polybar/config" = "/home/anna/.config/polybar/config"
